name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install libopencv-dev catch2 cppcheck lcov -y

    - name: Static analysis
      run: cppcheck ${{github.workspace}}

    - name: Configure CMake for tests and coverage
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/tests/build

    - name: Build tests
      run: cmake --build ${{github.workspace}}/tests/build

    - name: Run tests
      run: ${{github.workspace}}/tests/build/tests -s

    - name: Run test coverage
      run: |
        lcov --capture --directory . --output-file /tmp/coverage.info
        lcov --remove /tmp/coverage.info '*tests*' '*include*' -o /tmp/coverage.info

    - name: Configure CMake for builds
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build application
      run: cmake --build ${{github.workspace}}/build

    - name: Generate Debian packages
      run: cpack -G DEB -B ${{github.workspace}}/build --config build/CPackConfig.cmake
